### PR TITLE
Mongo tcp keepalive

### PR DESCRIPTION
**Pull request by BerniVarga**

### CODE REVIEW

**Comment by kovacshuni** [comment]
If there were some hack to extract that keep-alive time value into the config, but i can't think of a good way, without using a constant. @martingartonft any go hacks?

**Comment by martingartonft** [comment]
Looks good. Hard coding fine for now on the 30 seconds value.

**Comment by kovacshuni** [comment]
+1

**Comment by catalin-ilea** [comment]
lgtm

**Pull request merged**
