### PR TITLE
Revert "Merge pull request #10 from Financial-Times/add-uniq-index"

### PR DESCRIPTION
**Pull request by tamas-molnar**
This reverts commit 0427e1d4a832f81f3b5d000a3f45c1c886b8ceed, reversing
changes made to 484b57e7f0b79fde0674555db3ab114cef64daa9.

* we need to do this before nativerw can be released, we're not ready to release this yet

### CODE REVIEW

**Comment by khatton-ft** [comment]
Why are we no longer requiring unique UUIDs?

**Comment by tamas-molnar** [comment]
@khatton-ft This was never released in prod because it means re-indexing the DB, which blocks operations on the DB. It was meant to be released after we decouple nativerw from the publishing flow, but that hasn't happened yet.

**Comment by kovacshuni** [comment]
+1

**Comment by khatton-ft** [comment]
:+1:

**Pull request merged**
